site_name: my-project
repo_url: https://gitlab.com/frkl/my-project
site_author: Markus Binsteiner
docs_dir: docs
site_dir: build/site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking

markdown_extensions:
- attr_list
- admonition
- codehilite:
    guess_lang: false
- toc:
    permalink: true
- pymdownx.snippets:
    base_path: docs

nav:
- Home: index.md
- Install: install.md
- Usage: usage.md
- About: about.md

plugins:
- search
- mkdocstrings:
    default_handler: python
    watch:
      - "src"
- frkl-docgen:
    main_module: "my_project"
- macros:
   modules:
     - frkl.project.documentation.mkdocs_macros_frkl
